# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4960c5ef936e133fc8aad5add944f73990a2af4ad99e6a31061272ee668200dd89070db10d9115dd1d27d8b1b75cff52c8e89f4a792289c6cc8ad10092129fbf

test:
  secret_key_base: fe132f5342aafbe332d09515cd1b8d40c1540c9a2f832495f71228c3d02eeea4ebee3e135dd295d50724397a87cee8549a9816584dd483778a81c12b55c012cd

# Keep a copy of the production secret key in a secure location and 
# read the key from the environment when running the application.
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
